In [1]:
import numpy as np

In [3]:
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])

In [4]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [8]:
b=np.arange(0,3)

In [9]:
b

array([0, 1, 2])

In [15]:
a=np.arange(0,40,10)

In [16]:
a

array([ 0, 10, 20, 30])

In [20]:
a=a.reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [23]:
b=np.arange(0,3)
b

array([0, 1, 2])

In [24]:
a+b  #here is brodcasting happen

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])