In [11]:
import numpy as np

In [18]:
data = np.loadtxt('fit.txt',dtype='str')

C:\Users\Aadarsh kumar\AppData\Local\Temp\ipykernel_7508\2072195262.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt('fit.txt',dtype='str')


In [19]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [21]:
data.shape

(96, 6)

In [22]:
data.ndim

2

In [23]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [25]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [27]:
a=np.array(range(16))

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
a.shape

(16,)

In [31]:
a.shape[0]

16

In [32]:
type(a)

numpy.ndarray

In [33]:
type(data)

numpy.ndarray

# Reshape

In [37]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
a.reshape(8,2)    #original shape will not change

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [42]:
a.reshape(4,5)  # error because element is less (4X5 need 20 element)

ValueError: cannot reshape array of size 16 into shape (4,5)

In [45]:
a.reshape(3,5)  # error because elemet is more then what matrix needed (3X5 need 15 element)

ValueError: cannot reshape array of size 16 into shape (3,5)

In [50]:
a.reshape(2,8,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]]])

In [51]:
a.ndim

1

In [58]:
a=np.arange(10,101,10)

In [59]:
a.shape

(10,)

In [64]:
a.reshape(2,-1)  #unknown dimension

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [66]:
a.reshape(5,-1)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [67]:
a.reshape(3,-1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

In [68]:
a.reshape(-1,-1) #can only specify one unknown dimension

ValueError: can only specify one unknown dimension

In [69]:
a=np.arange(10,200,10)

In [70]:
len(a)

19

In [71]:
a.reshape(4,-1)

ValueError: cannot reshape array of size 19 into shape (4,newaxis)

In [72]:
a=np.arange(10,201,10)

In [73]:
len(a)

20

In [81]:
a=a.reshape(4,-1)

In [83]:
a

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [84]:
a[0][0]

np.int64(10)

In [85]:
a[2][3]

np.int64(140)

In [86]:
a[0,0]

np.int64(10)

In [88]:
a[2,3]  #a[R,C]

np.int64(140)

In [90]:
a[1:3,2:4]

array([[ 80,  90],
       [130, 140]])

In [91]:
a

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [92]:
a[:,1]

array([ 20,  70, 120, 170])

In [93]:
a[:,1:2]

array([[ 20],
       [ 70],
       [120],
       [170]])

In [95]:
a1=np.arange(10,91,10)

In [96]:
 a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
a1[[2,3]]

array([30, 40])

In [99]:
a1[[3,8]]

array([40, 90])

In [100]:
a

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [101]:
a[[0],[0]]

array([10])

In [102]:
a[[0,1,2],[0,1,2]]

array([ 10,  70, 130])

## Task

In [103]:
a3=np.arange(10,91,10)

In [104]:
a3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [108]:
a3=a3.reshape(3,-1)

In [110]:
a3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [111]:
a3[[0,1,2],[0,1,2]]

array([10, 50, 90])

In [113]:
a3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [115]:
a3.T  #Transpose of original matrix

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

In [116]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [117]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [119]:
data_T=data.T

In [120]:
data_T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [121]:
data.shape

(96, 6)

In [122]:
data_T.shape

(6, 96)

In [124]:
a,b=[7,8]

In [126]:
a

7

In [127]:
b

8

In [128]:
date,step_count,mood,calories_burned,hours_of_sleep,activity_status=data_T

In [129]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [130]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [131]:
#date,step_count,mood,calories_burned,hours_of_sleep,activity_status=data_T

In [132]:
hours_of_sleep

array(['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
       '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
       '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
       '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
       '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
       '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
       '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
       '2', '8', '5', '5', '5'], dtype='<U10')

In [135]:
step_count.astype('int')  #converted to integer

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [137]:
calories_burned

array(['181', '197', '0', '174', '223', '149', '140', '38', '1', '40',
       '101', '152', '150', '113', '49', '86', '6', '99', '143', '125',
       '129', '6', '9', '10', '72', '150', '141', '156', '57', '72', '17',
       '181', '197', '131', '154', '137', '193', '19', '101', '139',
       '164', '137', '22', '17', '9', '145', '192', '146', '234', '167',
       '16', '17', '32', '35', '220', '116', '23', '44', '131', '86',
       '194', '60', '121', '76', '93', '53', '25', '227', '125', '243',
       '14', '39', '55', '158', '7', '213', '116', '129', '21', '28',
       '16', '180', '138', '176', '99', '5', '1', '10', '47', '84', '23',
       '4', '0', '0', '0', '0'], dtype='<U10')

In [138]:
np.array(calories_burned,dtype='int')  #converted to integer

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [139]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [144]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [146]:
mood.unique  #canot used as an array

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [147]:
activity_status

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [148]:
np.unique(activity_status)

array(['Active', 'Inactive'], dtype='<U10')

## masking

In [150]:
m1=np.arange(12).reshape(3,-1)

In [151]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
m1>6

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [153]:
m1[m1>6]

array([ 7,  8,  9, 10, 11])

In [155]:
 # why above converted 2D-1D? because of formating 

In [156]:
date.shape

(96,)

In [159]:
activity_status.shape

(96,)

In [160]:
mood=='Happy'

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [165]:
fill=mood=='Happy'

In [166]:
fill

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [167]:
step_count[fill]

array(['4732', '330', '4550', '4435', '4779', '1831', '2255', '539',
       '5464', '4068', '4683', '4033', '6314', '614', '3149', '4005',
       '4880', '4136', '705', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '3608', '774', '1421', '4064', '2725',
       '5934', '1867', '7422', '5537', '5376', '153', '2203'],
      dtype='<U10')

In [169]:
step_count[mood=='Sad']

array(['6041', '25', '5461', '4545', '4340', '1230', '61', '1258', '3148',
       '4687', '3519', '1580', '2822', '181', '6676', '3721', '1648',
       '799', '1696', '221', '4061', '651', '753', '518', '177', '36',
       '299', '702', '133'], dtype='<U10')

## Aggregate function

In [170]:
a=np.arange(1,5)

In [171]:
a

array([1, 2, 3, 4])

In [175]:
np.sum(a)

np.int64(10)

In [176]:
np.mean(a)

np.float64(2.5)

In [177]:
np.max(a)

np.int64(4)

In [178]:
np.min(a)

np.int64(1)

In [179]:
np.count_nonzero(a)

4

In [180]:
a=np.arange(1,10,1).reshape(3,-1)

In [181]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [183]:
np.sum(a) #sum all the value 

np.int64(45)

In [184]:
np.max(a)

np.int64(9)

In [185]:
np.min(a)

np.int64(1)

In [188]:
#axis=0 - column # axis=1 -ROWs  

In [187]:
np.max(a,axis=0)

array([7, 8, 9])

In [189]:
np.max(a,axis=1)

array([3, 6, 9])

In [190]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])

In [191]:
a,b

(array([1, 2, 3, 4]), array([4, 3, 2, 1]))

In [192]:
a>b

array([False, False,  True,  True])

In [193]:
a<b

array([ True,  True, False, False])

In [194]:
a==b

array([False, False, False, False])

In [198]:
np.any(a>b)

np.True_

In [199]:
np.all(a>b)

np.False_

In [202]:
np.all([True,False])

np.False_

In [203]:
np.all([True,True])

np.True_

In [204]:
np.all([False,False])

np.False_

In [205]:
arr=np.array([-3,4,27,34,-2,0,-45,-11,4,0])

In [206]:
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [207]:
np.where(arr<0,"wrong value","correct value")  #print wriong value if value is less then 0

array(['wrong value', 'correct value', 'correct value', 'correct value',
       'wrong value', 'correct value', 'wrong value', 'wrong value',
       'correct value', 'correct value'], dtype='<U13')

In [208]:
#date,step_count,mood,calories_burned,hours_of_sleep,activity_status=data_T

In [212]:
step_count_Happy=step_count[mood=='Happy']
len(step_count_Happy)

40

In [213]:
step_count_Sad=step_count[mood=='Sad']
len(step_count_Sad)

29

In [214]:
step_count_neutral=step_count[mood=='Neutral']
len(step_count_neutral)

27

In [216]:
step_count_happpy_neutral=step_count[(mood =='Neutral') | (mood=='Happy')]
len(step_count_happpy_neutral)

67

In [219]:
np.mean(step_count_Sad.astype('int'))

np.float64(2103.0689655172414)

In [220]:
np.mean(step_count_Happy.astype('int'))

np.float64(3392.725)

In [222]:
np.mean(step_count_neutral.astype('int'))

np.float64(3153.777777777778)

In [223]:
step_count.astype('int')

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [225]:
mood[step_count.astype('int')>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [231]:
np.unique(mood[step_count.astype('int')>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

# Summarize